apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: kumar1996/kubetest
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "curl -s https://consul.moengage.com/v1/kv/presto-test/config.properties  | jq -r '.[] | .Value' | base64 --decode > /etc/kube.properties"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
